apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::522751423049:role/eksctl-udacitycluster-nodegroup-n-NodeInstanceRole-QNUV54Q7UR1C
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::522751423049:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-07-29T00:17:40Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "14517"
  uid: 119def21-05a6-4a2a-abc3-0d60b87c15d6
